#ifndef __MESSAGETYPE_H__
#define __MESSAGETYPE_H__

typedef enum {
    // RECEIVED MESSAGE TYPES
    REQ_ACK,
    REQ_MANUAL_CONTROL,
    REQ_RECORD,
    REQ_START_DRONE,
    REQ_DRONE_INFOS,
    // TO SEND MESSAGE TYPES
    RESP_ACK,
    RESP_START_DRONE,
    RESP_RECORD,
    RESP_DRONE_INFOS,
    // GLOBAL
    UNKNOWN
} MESSAGE_TYPE;
#endif // __MESSAGETYPE_H__